// <auto-generated />
using System;
using FunctionalKanban.Infrastructure.SqlServer.ViewProjectionDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FunctionalKanban.Infrastructure.SqlServer.ViewProjectionDatabase.Migrations
{
    [DbContext(typeof(ViewProjectionDbContext))]
    partial class ViewProjectionDatabaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FunctionalKanban.Core.Domain.ViewProjections.DeletedTaskViewProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueIdentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("DeletedAt");

                    b.HasKey("Id");

                    b.ToTable("DeletedTasks");
                });

            modelBuilder.Entity("FunctionalKanban.Core.Domain.ViewProjections.ProjectViewProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueIdentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<long>("TotalRemaningWork")
                        .HasColumnType("integer")
                        .HasColumnName("TotalRemaningWork");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("FunctionalKanban.Core.Domain.ViewProjections.TaskViewProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueIdentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("EfProjectId")
                        .HasColumnType("uniqueIdentifier")
                        .HasColumnName("ProjectId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Name");

                    b.Property<long>("RemaningWork")
                        .HasColumnType("integer")
                        .HasColumnName("RemaningWork");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
