// <auto-generated />
using System;
using FunctionalKanban.Infrastructure.SqlServer.EventDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FunctionalKanban.Infrastructure.SqlServer.EventDatabase.Migrations
{
    [DbContext(typeof(EventDbContext))]
    partial class EventDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FunctionalKanban.Infrastructure.SqlServer.EventDatabase.EfEntities.EventEfEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueIdentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueIdentifier")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("EntityName");

                    b.Property<byte[]>("EventDatas")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Datas");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime")
                        .HasColumnName("CreationDate");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
